/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.event.KeyListener;

/**
 *
 * @author Andrew
 */
public class TabBar extends javax.swing.JPanel
{
    public TabBar()
    {
        initComponents();
    }
    
    /**
     * Creates new form TabBar
     * @param labelText
     * @param buttonText
     */
    public TabBar(String labelText, String buttonText)
    {
        initComponents();
        jButton1.setFocusable(false);
        jButton1.setText(buttonText);
        jLabel1.setText(labelText);
    }
    
    public String getLabelText()
    {
        return jLabel1.getText();
    }
    
    public void setLabelText(String text)
    {
        jLabel1.setText(text);
    }
    
    public void addTabCloseActionListener(java.awt.event.ActionListener al)
    {
        jButton1.addActionListener(al);
    }
    
    public void addTabCloseKeyListener(KeyListener kl)
    {
        jButton1.addKeyListener(kl);
    }
    
    public void setButtonToolTipText(String text)
    {
        jButton1.setToolTipText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove-16.png"))); // NOI18N
        jButton1.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
